test:
	erlc test.erl bs01.erl bs02.erl bs03.erl bs04.erl
	erl -s test run

test_1:
	erlc test.erl bs01.erl
	erl -s test run bs01 test

test_2:
	erlc test.erl bs02.erl
	erl -s test run bs02 test

test_3:
	erlc test.erl bs03.erl
	erl -s test run bs03 test

test_4:
	erlc test.erl bs04.erl
	erl -s test run bs04 test
