test:
	erlc test.erl p01.erl p02.erl p03.erl p04.erl p05.erl p06.erl p07.erl p08.erl p09.erl p10.erl p11.erl p12.erl p13.erl p14.erl p15.erl p16.erl p17.erl p18.erl p19.erl p20.erl p21.erl p22.erl p23.erl p24.erl p25.erl p26.erl p27.erl p28.erl p31.erl p32.erl p33.erl p34.erl p35.erl p36.erl p37.erl 
	erl -s test run

test_1:
	erlc test.erl p01.erl
	erl -s test run p01 test

test_2:
	erlc test.erl p02.erl
	erl -s test run p02 test

test_3:
	erlc test.erl p03.erl
	erl -s test run p03 test

test_4:
	erlc test.erl p04.erl
	erl -s test run p04 test

test_5:
	erlc test.erl p05.erl
	erl -s test run p05 test

test_6:
	erlc test.erl p06.erl
	erl -s test run p06 test

test_7:
	erlc test.erl p08.erl
	erl -s test run p08 test

test_8:
	erlc test.erl p08.erl
	erl -s test run p08 test

test_9:
	erlc test.erl p09.erl
	erl -s test run p09 test

test_10:
	erlc test.erl p10.erl
	erl -s test run p10 test

test_11:
	erlc test.erl p11.erl
	erl -s test run p11 test

test_12:
	erlc test.erl p12.erl
	erl -s test run p12 test

test_13:
	erlc test.erl p13.erl
	erl -s test run p13 test

test_14:
	erlc test.erl p14.erl
	erl -s test run p14 test

test_15:
	erlc test.erl p15.erl
	erl -s test run p15 test

test_16:
	erlc test.erl p16.erl
	erl -s test run p16 test

test_17:
	erlc test.erl p17.erl
	erl -s test run p17 test

test_18:
	erlc test.erl p18.erl
	erl -s test run p18 test

test_19:
	erlc test.erl p19.erl
	erl -s test run p19 test

test_20:
	erlc test.erl p20.erl
	erl -s test run p20 test

test_21:
	erlc test.erl p21.erl
	erl -s test run p21 test

test_22:
	erlc test.erl p22.erl
	erl -s test run p22 test

test_23:
	erlc test.erl p23.erl
	erl -s test run p23 test

test_24:
	erlc test.erl p24.erl
	erl -s test run p09 test

test_25:
	erlc test.erl p25.erl
	erl -s test run p26 test

test_26:
	erlc test.erl p26.erl
	erl -s test run p26 test

test_27:
	erlc test.erl p27.erl
	erl -s test run p27 test

test_28:
	erlc test.erl p28.erl
	erl -s test run p28 test

test_31:
	erlc test.erl p31.erl
	erl -s test run p31 test

test_32:
	erlc test.erl p32.erl
	erl -s test run p32 test

test_33:
	erlc test.erl p33.erl
	erl -s test run p33 test

test_33:
	erlc test.erl p33.erl
	erl -s test run p33 test

test_34:
	erlc test.erl p34.erl
	erl -s test run p34 test

test_35:
	erlc test.erl p35.erl
	erl -s test run p35 test

test_36:
	erlc test.erl p36.erl
	erl -s test run p36 test

test_37:
	erlc test.erl p37.erl
	erl -s test run p37 test
