test:
	erlc test.erl p01.erl p02.erl p03.erl p04.erl p05.erl p06.erl p07.erl p08.erl p09.erl p10.erl p11.erl p12.erl p13.erl p14.erl p15.erl
	erl -s test run

test_1:
	erlc test.erl p01.erl
	erl -s test run p01 test

test_2:
	erlc test.erl p02.erl
	erl -s test run p02 test

test_3:
	erlc test.erl p03.erl
	erl -s test run p03 test

test_4:
	erlc test.erl p04.erl
	erl -s test run p04 test

test_5:
	erlc test.erl p05.erl
	erl -s test run p05 test

test_6:
	erlc test.erl p06.erl
	erl -s test run p06 test

test_7:
	erlc test.erl p08.erl
	erl -s test run p08 test

test_8:
	erlc test.erl p08.erl
	erl -s test run p08 test

test_9:
	erlc test.erl p09.erl
	erl -s test run p09 test

test_10:
	erlc test.erl p10.erl
	erl -s test run p10 test

test_11:
	erlc test.erl p11.erl
	erl -s test run p11 test

test_12:
	erlc test.erl p12.erl
	erl -s test run p12 test

test_13:
	erlc test.erl p13.erl
	erl -s test run p13 test

test_14:
	erlc test.erl p14.erl
	erl -s test run p14 test

test_15:
	erlc test.erl p15.erl
	erl -s test run p15 test
